name: Create and Push Tag

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create and push tag
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          VERSION="v1.1"
          echo "Creating tag $VERSION"
          git tag $VERSION
          git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}.git
          git push origin --tags
