name: Create and Push Tag

on:
  workflow_dispatch:
    inputs:
      type:
        description: 'Type of version bump (major, minor, patch)'
        required: false
        default: 'patch'

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Récupérer tout le repo avec les tags
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          tags: true

      # 2️⃣ Configurer Git
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # 3️⃣ Déterminer le nouveau tag
      - name: Determine new version
        id: new_version
        run: |
          TYPE="${{ github.event.inputs.type }}"
          
          # Récupérer le dernier tag
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "Last tag: $LAST_TAG"
          
          MAJOR=$(echo $LAST_TAG | cut -d. -f1 | sed 's/v//')
          MINOR=$(echo $LAST_TAG | cut -d. -f2)
          PATCH=$(echo $LAST_TAG | cut -d. -f3)
          
          if [ "$TYPE" == "major" ]; then
            MAJOR=$((MAJOR + 1))
            MINOR=0
            PATCH=0
          elif [ "$TYPE" == "minor" ]; then
            MINOR=$((MINOR + 1))
            PATCH=0
          else
            PATCH=$((PATCH + 1))
          fi
          
          NEW_TAG="v$MAJOR.$MINOR.$PATCH"
          echo "New tag: $NEW_TAG"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

      # 4️⃣ Créer le tag uniquement s’il n’existe pas déjà
      - name: Create and push tag
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          if git rev-parse "$NEW_TAG" >/dev/null 2>&1; then
            echo "Tag $NEW_TAG already exists, skipping creation."
          else
            git tag $NEW_TAG
            git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}.git
            git push origin $NEW_TAG
            echo "Tag $NEW_TAG pushed successfully."
          fi
